name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install tests dependencies
      run: dotnet restore HLHML.Test/HLHML.Test.csproj

    - name: Build test
      run: dotnet build HLHML.Test/HLHML.Test.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test HLHML.Test/HLHML.Test.csproj --no-restore --verbosity normal --filter Future!=true

    #- name: Install console tests dependencies
    #  run: dotnet restore HLHML.Console.Test/HLHML.Console.Test.csproj

    #- name: Build console test
    #  run: dotnet build HLHML.Console.Test/HLHML.Console.Test.csproj --configuration Release --no-restore

    #- name: Test console
    #  run: dotnet test HLHML.Console.Test/HLHML.Console.Test.csproj --no-restore --verbosity normal --filter Future!=true

    - name: Install HLHML dependencies
      run: dotnet restore HLHML/HLHML.csproj

    - name: Build HLHML
      run: dotnet build HLHML/HLHML.csproj --configuration Release --no-restore
      
    - name: Publish HLHML to Nuget.Org
      if: success() && github.ref == 'refs/heads/master'
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: HLHML/HLHML.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}